name: 'Close stale Issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    env:
      repo-token: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # stale and delete issues
          stale-issue-message: '🤖 meep morp! This Issue is now marked as stale because there has been no activity for a while.  The Issue may be unassigned and moved to the Backlog or it will get deleted if there is no activity in the next 7 days.'
          close-issue-message: '🤖 meep morp :( This Issue has been closed because it was stale for 7 days.'
          days-before-issue-stale: 21
          days-before-issue-close: 7

          # stale pull requests
          stale-pr-message: '🤖 meep morp! This PR is now marked as stale because there has been no activity for a while.  Please guarantee this is still a relevant PR.'
          days-before-pr-stale: 14
          days-before-pr-close: -1 # Applying a negative value means the pr will not be closed and is simply being marked as stale
