name: Welcome First Time Contributor
on: [pull_request, issues]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          issue-message: "🤖 meep morp! Welcome! Your first issue has been assigned, congrats!  Remember to review our documentation if you have any questions or reach out in the comments if needed.  We're excited to have you onboard - have fun!"
          pr-message: "🤖 meep morp! Well done on submitting your first PR - the core team will review this soon and may ask for some changes.  Depending on how much is happening it may take a few days to hear back, you're real close to shipping your first contribution though so hang in there 😬"
